# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go run cmd/main.go -o README.md -t ${{ secrets.UPDATE_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "xiaoler"
        git config --global user.email "scholer_l@live.com"

    - name: Commit to Git
      run: |
        git add README.md
        git commit -m "Update README.md"
        git push
